[user]
name = "John Kurkowski"

[ui]
bookmark-list-sort-keys = ["committer-date-", "name"]
default-command = "log"
diff-editor = ":builtin"
diff-formatter = "delta"

[merge-tools.delta]
diff-args=["--side-by-side", "$left", "$right", "--width=$width"]
diff-expected-exit-codes = [0, 1]
